version: '3'
services:
  ethereum:
    build:
      context: ./
      dockerfile: docker/ganache.Dockerfile
    ports:
      - 8545:8545
    restart: unless-stopped
    environment:
      FORK_URL: "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
      FORK_BLOCK_NUMBER: 14068798

  polygon:
    build:
      context: ./
      dockerfile: docker/ganache.Dockerfile
    ports:
      - 8546:8545
    restart: unless-stopped
    environment:
      FORK_URL: "https://polygon-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
      FORK_BLOCK_NUMBER: 24108240
