version: '3'
services:
  ethereum:
    build:
      context: ./
      dockerfile: docker/ganache.Dockerfile
    ports:
      - 8545:8545
    restart: unless-stopped
    environment:
      MNEMONIC: "test test test test test test test test test test test junk"
      FORK_URL: "${MAINNET_ALCHEMY_API_ENDPOINT}"
      FORK_BLOCK_NUMBER: 14068798
      CHAIN_ID: 1

  polygon:
    build:
      context: ./
      dockerfile: docker/ganache.Dockerfile
    ports:
      - 8546:8545
    restart: unless-stopped
    environment:
      MNEMONIC: "test test test test test test test test test test test junk"
      FORK_URL: "${POLYGON_ALCHEMY_API_ENDPOINT}"
      FORK_BLOCK_NUMBER: 24108240
      CHAIN_ID: 137
