version: '3'
services:
  ethereum:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 8545:8545
    restart: unless-stopped
    environment:
      MNEMONIC: "test test test test test test test test test test test junk"
      FORK_URL: "${MAINNET_ALCHEMY_API_ENDPOINT}"
      FORK_BLOCK_NUMBER: 14068798
      CHAIN_ID: 1
      DEPLOY_TAGS: "ethereum"
      # these keys need to exist because hardhat.config.ts demands it
      # they're not really used here
      ALCHEMY_API_KEY: "${MAINNET_ALCHEMY_API_KEY}"
      MAINNET_PK: "0000000000000000000000000000000000000000000000000000000000000001"
      TESTNET_PK: "0000000000000000000000000000000000000000000000000000000000000001"

  polygon:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 8546:8545
    restart: unless-stopped
    environment:
      MNEMONIC: "test test test test test test test test test test test junk"
      FORK_URL: "${POLYGON_ALCHEMY_API_ENDPOINT}"
      FORK_BLOCK_NUMBER: 24108240
      CHAIN_ID: 137
      DEPLOY_TAGS: "polygon"
      # these keys need to exist because hardhat.config.ts demands it
      # they're not really used here
      ALCHEMY_API_KEY: "${POLYGON_ALCHEMY_API_KEY}"
      MAINNET_PK: "0000000000000000000000000000000000000000000000000000000000000001"
      TESTNET_PK: "0000000000000000000000000000000000000000000000000000000000000001"
